export const APP_CONSTANTS = {
  ROUTES: {
    LOGIN: "/login",
    DASHBOARD: "/",
    JOURNAL: "/journal",
    REPORTS: "/reports",
    DOCUMENTS: "/documents",
  },
  API_ENDPOINTS: {
    TOKEN: "/api/token/",
    ME: "/api/users/me/",
    GROUPS: "/api/group/",
    SUBJECTS: "/api/subjects/",
    CADETS: "/api/cadet/",
    STUDENTS: "/api/student/",
    MARK_KINDS: "/api/mark-kind/",
    MARK_VALUES: "/api/mark-values/",
    LESSON_TIMES: "/api/lesson-times/",
    ATTENDANCE_REASONS: "/api/attendance-reasons/",
    LESSONS: "/api/lessons/",
    ATTENDANCES: "/api/attendances/",
    JOURNAL_RECORDS: "/api/journal-records/",
    LESSON_TYPES: "/api/lesson-types/",
    SEMESTERS: "/api/semesters/",
    TEACHERS: "/api/readonly-users/",
  },
  STORAGE_KEYS: { TOKEN: "kis_access_token", USER: "kis_user" },
  STUDENT_TYPES: { CADET: "cadet", STUDENT: "student" },
  HTTP_STATUS: {
    UNAUTHORIZED: 401,
  },
  GRID: {
    MIN_COLUMNS: 10,
    MIN_ROWS: 15,
  },
  UI: {
    APP_TITLE: "Журнал учета посещаемости и отметок обучающихся",
    LOGIN_SUBTITLE: "Войдите в свой аккаунт",
    DASHBOARD_TITLE: "Выберите раздел",
    ABSENT_MARK: "Н",
    LESSON_SUFFIX: "пара",
    DEFAULT_ATTENDANCE: "Не указано (Присутствует)",
    DEFAULT_MARK: "Нет отметки",
    NO_TOPIC: "Без темы",
    LABELS: {
      USERNAME: "Имя пользователя",
      PASSWORD: "Пароль",
      LOGIN_BTN: "Авторизоваться",
      LOGOUT_BTN: "Выйти",
      JOURNAL: "Журнал",
      REPORTS: "Отчетность",
      DOCUMENTS: "Документы",
      GROUP: "Группа",
      SUBJECT: "Дисциплина",
      DATE: "Дата",
      LESSON_TIME: "Пара",
      LESSON_TYPE: "Тип занятия",
      MARK_KIND: "Вид контроля",
      TOPIC: "Тема занятия",
      TEACHERS: "Преподаватели",
      ATTENDANCE: "Посещаемость",
      MARK: "Отметка",
      MARK_VALUE: "Оценка",
      MARK_KIND_TYPE: "Тип",
      FULL_NAME: "ФИО",
      ABSENT: "Отсутствует",
      CANCEL: "Отмена",
      SAVE: "Сохранить",
      ADD: "Добавить",
      ADD_LESSON: "Добавить занятие",
    },
    PLACEHOLDERS: {
      SELECT_GROUP: "-- Выберите группу --",
      SELECT_SUBJECT: "-- Выберите дисциплину --",
      SELECT_LESSON_TIME: "Выберите пару",
      SELECT_DATE: "Выберите дату",
      SELECT_TEACHERS: "Выберите преподавателей",
    },
    MESSAGES: {
      SELECT_FILTERS: "Выберите группу и дисциплину",
      LOADING: "Загрузка данных...",
      NO_MARKS: "Нет оценок",
      UNDER_CONSTRUCTION: "Раздел в разработке",
    },
    ERRORS: {
      LOGIN: "Ошибка авторизации. Попробуйте еще раз.",
      SAVE_DATA: "Ошибка при сохранении данных",
      ADD_LESSON: "Ошибка при добавлении занятия",
    },
    ERROR_SUMMARY: "Ошибка",
  },
};
