export const APP_CONSTANTS = {
  ROUTES: {
    LOGIN: "/login",
    DASHBOARD: "/",
    JOURNAL: "/journal",
    REPORTS: "/reports",
    ATTENDANCE: "/attendance",
  },
  ROUTE_NAMES: {
    LOGIN: "Login",
    DASHBOARD: "Dashboard",
    JOURNAL: "Journal",
    REPORTS: "Reports",
    ATTENDANCE: "Attendance",
  },
  API_ENDPOINTS: {
    TOKEN: "/api/token/",
    ME: "/api/users/me/",
    GROUPS: "/api/group/",
    ACTIVE_GROUPS: "/api/group/get_active_groups/",
    SUBJECTS: "/api/subjects/",
    CADETS: "/api/cadet/",
    STUDENTS: "/api/student/",
    CADETS_SHORT: "/api/cadet/short-list/",
    STUDENTS_SHORT: "/api/student/short-list/",
    MARK_VALUES: "/api/mark-values/",
    LESSON_TIMES: "/api/lesson-times/",
    ATTENDANCE_REASONS: "/api/attendance-reasons/",
    LESSONS: "/api/lessons/",
    ATTENDANCES: "/api/attendances/",
    JOURNAL_RECORDS: "/api/journal-records/",
    LESSON_TYPES: "/api/lesson-types/",
    TEACHERS: "/api/readonly-users/",
    SEMESTERS: "/api/semesters/",
    FACULTIES: "/api/subdivision/",
    SPECIALTIES: "/api/speciality/",
    YEARS: "/api/year/",
    REPORTS_PERFORMANCE: "/api/reports/performance/",
    REPORTS_ATTENDANCE: "/api/reports/attendance/",
    ACADEMIC_CARD: "/api/academic-card/download/",
  },
  ENDPOINTS_SUFFIX: {
    SYNC_MARKS: "sync-marks/",
    DOWNLOAD_VEDOMOST: "/download-vedomost/",
    DOWNLOAD_STUDENT_CARD: "/download-student-card/",
    DOWNLOAD_ROSTER: "/download-roster/",
    BULK: "bulk/",
    BULK_DELETE: "bulk-delete/",
  },
  NETWORK: {
    AUTH_PREFIX: "Bearer ",
    CONTENT_TYPE_JSON: "application/json",
    RESPONSE_TYPE_BLOB: "blob",
    HEADER_CONTENT_DISPOSITION: "content-disposition",
  },
  FIELD_TYPES: {
    TEXT: "text",
    NUMBER: "number",
    BOOLEAN: "boolean",
    TIME: "time",
    DATE: "date",
    SELECT: "select",
  },
  API_FALLBACK_RESPONSE: { data: [] },
  STORAGE_KEYS: {
    TOKEN: "kis_access_token",
    USER: "kis_user",
    JOURNAL_HELP_HIDE: "kis_hide_journal_help",
    ATTENDANCE_HELP_HIDE: "kis_hide_attendance_help",
    REPORTS_HELP_HIDE: "kis_hide_reports_help",
    JOURNAL_GROUP: "kis_journal_group",
    JOURNAL_SUBJECT: "kis_journal_subject",
    ATTENDANCE_GROUP: "kis_attendance_group",
  },
  STUDENT_TYPES: {
    CADET: "cadet",
    STUDENT: "student",
  },
  HTTP_STATUS: {
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
  },
  GRID: {
    MIN_COLUMNS: 10,
    MIN_ROWS: 15,
    DEFAULT_PAGINATION_ROWS: 10,
    MAX_ATTENDANCE_DAYS: 31,
  },
  NOTIFY: {
    LIFE_MS: 2500,
  },
  KEYBOARD: {
    ENTER: "Enter",
    ESCAPE: "Escape",
  },
  JOURNAL_QUICK_FILTERS: {
    ALL: "all",
    NO_MARKS: "no_marks",
    WITH_ABSENCES: "absences",
    WITH_RETAKES: "retakes",
  },
  TIMERS: {
    INLINE_EDIT_DELAY: 250,
    INLINE_EDIT_CLOSE: 150,
    INLINE_EDIT_FOCUS: 50,
    INLINE_EDIT_SAVE: 50,
  },
  LESSON_HOURS_OPTIONS: [2, 4, 6, 8],
  LOCALES: {
    RU: "ru-RU",
  },
  LOCALE_CONFIG: {
    firstDayOfWeek: 1,
    dayNames: [
      "Воскресенье",
      "Понедельник",
      "Вторник",
      "Среда",
      "Четверг",
      "Пятница",
      "Суббота",
    ],
    dayNamesShort: ["Вск", "Пнд", "Втр", "Срд", "Чтв", "Птн", "Сбт"],
    dayNamesMin: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
    monthNames: [
      "Январь",
      "Февраль",
      "Март",
      "Апрель",
      "Май",
      "Июнь",
      "Июль",
      "Август",
      "Сентябрь",
      "Октябрь",
      "Ноябрь",
      "Декабрь",
    ],
    monthNamesShort: [
      "Янв",
      "Фев",
      "Мар",
      "Апр",
      "Май",
      "Июн",
      "Июл",
      "Авг",
      "Сен",
      "Окт",
      "Ноя",
      "Дек",
    ],
    today: "Сегодня",
    clear: "Очистить",
    dateFormat: "dd.mm.yy",
    weekHeader: "Нед",
  },
  FORMATTING: {
    SEPARATOR: ", ",
    COMMA: ",",
    NEWLINE: "\n",
    TIME_SEPARATOR: ":",
    HOUR_FORMAT_24: "24",
  },
  DATE_FORMAT: {
    TWO_DIGIT: "2-digit",
    PAD_CHAR: "0",
    PAD_LENGTH: 2,
  },
  RULES: {
    MS_PER_DAY: 86400000,
    DAYS_PER_WEEK: 7,
    MONDAY_FIRST_DAY_OFFSET: 6,
    WEEK_OFFSET_CURRENT: 0,
    WEEK_OFFSET_PREV: -1,
    WEEK_OFFSET_NEXT: 1,
    DATE_RANGE_LENGTH: 2,
    REGEX_MATCH_LENGTH: 2,
    DEFAULT_LESSON_NUMBER: 0,
    TIME_STRING_LENGTH: 5,
    TIME_SUBSTRING_START: 0,
    TIME_SUBSTRING_END: 5,
    START_OF_DAY_HOURS: 0,
    START_OF_DAY_MINUTES: 0,
    START_OF_DAY_SECONDS: 0,
    START_OF_DAY_MS: 0,
    END_OF_DAY_HOURS: 23,
    END_OF_DAY_MINUTES: 59,
    END_OF_DAY_SECONDS: 59,
    END_OF_DAY_MS: 999,
    HTML_DOCTYPE: "<!doctype html",
    HTML_TAG: "<html",
  },
  FILES: {
    VEDOMOST_PREFIX: "vedomost_",
    STUDENT_CARD_PREFIX: "vypiska_iz_uchebnoy_kartochki_",
    ACADEMIC_CARD_PREFIX: "vypiska_",
    ROSTER_PREFIX: "roster_",
    VEDOMOST_EXT: ".docx",
    ACADEMIC_CARD_EXT: ".xlsx",
    REGEX_UTF8_FILENAME: /filename\*=UTF-8''([^;]+)/i,
    REGEX_FALLBACK_FILENAME: /filename="?([^"]+)"?/,
  },
  PREFIXES: {
    TEMP: "temp-",
    EMPTY_ROW: "empty-row-",
    EMPTY_DATE: "empty-date-",
    EMPTY_SUB: "empty-sub-",
    EMPTY_COL: "empty-col-",
    HEADER: "header-",
  },
  CSS_SELECTORS: {
    INLINE_EDITOR_INPUT: ".inline-editor input",
  },
  API_ERRORS: {
    UNIQUE_SET: "must make a unique set",
    LESSON_TIME: "lesson_time",
  },
  API_ERROR_KEYS: {
    DETAIL: "detail",
    ERROR: "error",
    NON_FIELD_ERRORS: "non_field_errors",
  },
  REPORT_FILTERS: {
    ALLOWED_FACULTIES: import.meta.env.VITE_ALLOWED_FACULTIES
      ? import.meta.env.VITE_ALLOWED_FACULTIES.split(",").map(Number)
      : [],
    ALLOWED_SPECIALTIES: import.meta.env.VITE_ALLOWED_SPECIALTIES
      ? import.meta.env.VITE_ALLOWED_SPECIALTIES.split(",").map(Number)
      : [],
  },
  ERROR_TRANSLATIONS: {
    "This field is required.": "Это поле обязательно для заполнения.",
    "You do not have permission to perform this action.":
      "Недостаточно прав для выполнения этого действия.",
    "must make a unique set": "Запись с такими параметрами уже существует.",
    lesson_time: "Время учебного занятия",
    date: "Дата",
    subject: "Дисциплина",
    group: "Группа",
    hours: "Количество учебных часов",
  },
  REPORT_TABS: {
    PERFORMANCE: "performance",
    ATTENDANCE: "attendance",
  },
  UI: {
    APP_TITLE: "Электронный журнал",
    LOGIN_SUBTITLE: "Войдите в свой аккаунт",
    DASHBOARD_TITLE: "Выберите раздел",
    LESSON_SUFFIX: "",
    DEFAULT_ATTENDANCE: "Не указано (Присутствует)",
    DEFAULT_MARK: "Нет отметки",
    NO_TOPIC: "Без темы",
    BREADCRUMB_SEPARATOR: "/",
    CRUD_DIALOG_WIDTH: "450px",
    PAGE_TITLES: {
      Journal: "Журнал",
      Reports: "Отчетность",
      Attendance: "Посещаемость",
    },
    LABELS: {
      HOME: "Главная",
      USERNAME: "Имя пользователя",
      PASSWORD: "Пароль",
      LOGIN_BTN: "Авторизоваться",
      LOGOUT_BTN: "Выйти",
      JOURNAL: "Журнал",
      REPORTS: "Отчетность",
      GROUP: "Группа",
      FACULTY: "Факультет",
      SPECIALTY: "Специальность",
      SUBJECT: "Дисциплина",
      DATE: "Дата",
      LESSON_TIME: "Пара",
      LESSON_TYPE: "Вид учебного занятия / форма аттестации",
      TOPIC: "Тема учебного занятия",
      TEACHERS: "Преподаватели",
      ATTENDANCE: "Посещаемость",
      MARK: "Отметка",
      MARK_VALUE: "Отметка",
      MAIN_MARK: "Основная:",
      RETAKE_MARK: "Пересдача",
      ADD_RETAKE: "Добавить пересдачу",
      ADD_MARK: "Добавить отметку",
      FULL_NAME: "ФИО",
      ABSENT: "Отсутствует",
      ABSENT_SHORT: "отсутств.",
      CANCEL: "Отмена",
      SAVE: "Сохранить",
      ADD: "Добавить",
      EDIT: "Редактировать",
      DELETE: "Удалить",
      ACTIONS: "Действия",
      ADD_LESSON: "Добавить учебное занятие",
      EDIT_LESSON: "Редактировать учебное занятие",
      DELETE_LESSON: "Удалить занятие",
      EDIT_LESSON_TITLE: "Редактировать занятие",
      FILTERS: "Фильтры",
      CLEAR_FILTERS: "Очистить фильтры",
      ATTENDANCE_REASONS: "Причина пропуска",
      REASON: "Причина",
      SEMESTER: "Полугодие",
      DATE_RANGE: "Период (С - ПО)",
      STUDENT: "Обучающийся",
      TEACHER: "Преподаватель",
      GENERATE_REPORT: "Сформировать отчет",
      TAB_PERFORMANCE: "Успеваемость",
      TAB_ATTENDANCE: "Посещаемость",
      YEAR: "Учебный год",
      YEAR_STR: "Учебный год (прописью)",
      START_TIME: "Время начала",
      END_TIME: "Время окончания",
      IS_ABSENT: "Считается отсутствием",
      START_DATE: "Дата начала",
      END_DATE: "Дата окончания",
      HOURS: "Учебные часы",
      PERIOD: "Период",
      SEARCH_BY_NAME: "Поиск по ФИО",
      OK: "OK",
      LEGEND: "",
      CURRENT_MARK: "Текущая отметка",
      RETAKEN_MARK: "Пересданная отметка",
      DOWNLOAD_VEDOMOST_TITLE: "Скачать ведомость",
      DOWNLOAD_STUDENT_CARD_TITLE: "Скачать выписку из учебной карточки",
      DOWNLOAD_ROSTER: "Скачать список группы",
      LESSON_NUMBER_SUFFIX: "пара",
      PREV: "Назад",
      NEXT: "Далее",
      ABSENCES_SHORT: "Пропуски",
      CONTINUE: "Продолжить",
      CURRENT_WEEK: "Эта неделя",
      PREV_WEEK: "Прошлая неделя",
      NEXT_WEEK: "Следующая неделя",
      REPEAT_LAST_TOPIC: "Взять тему прошлого занятия",
      SHOWN_COUNT: "Показано:",
      FILTER_ALL: "Все",
      FILTER_NO_MARKS: "Без оценок",
      FILTER_ABSENCES: "С пропусками",
      FILTER_RETAKES: "С пересдачами",
    },
    PLACEHOLDERS: {
      SELECT_GROUP: "-- Выберите группу --",
      SELECT_FACULTY: "-- Выберите факультет --",
      SELECT_SPECIALTY: "-- Выберите специальность --",
      SELECT_SUBJECT: "-- Выберите дисциплину --",
      SELECT_LESSON_TIME: "Выберите пару",
      SELECT_DATE: "Выберите дату",
      SELECT_PERIOD: "Выберите период",
      SELECT_TEACHERS: "Выберите преподавателей",
      SELECT_SEMESTER: "-- Выберите полугодие --",
      SELECT_STUDENT: "-- Выберите обучающегося --",
      SELECT_TEACHER: "-- Выберите преподавателя --",
      SELECT_MARK: "-- Выберите отметку --",
      SELECT_REASON: "-- Выберите причину --",
      SELECT_LESSON_TYPE: "-- Выберите вид учебного занятия --",
      SELECT_HOURS: "Выберите кол-во учебных часов",
      SEARCH_BY_NAME: "Поиск по ФИО...",
    },
    MESSAGES: {
      SELECT_FILTERS: "Выберите группу и дисциплину",
      SELECT_ATTENDANCE_FILTERS: "Выберите группу и дату",
      ATTENDANCE_SCOPE: "Область применения",
      SCOPE_PAIR: "Только эта пара",
      SCOPE_PAIRS: "Диапазон пар этого дня",
      SCOPE_DAYS: "Диапазон дней (все пары)",
      PAIR_FROM: "С пары",
      PAIR_TO: "По пару",
      DAY_FROM: "С даты",
      DAY_TO: "По дату",
      AFFECTED_COUNT: "Будет затронуто записей:",
      RANGE_TOO_LONG:
        "Максимальный период - 31 день. Пожалуйста, выберите более короткий период.",
      LOADING: "Загрузка данных...",
      SAVING: "Сохранение...",
      NO_MARKS: "Нет отметок",
      UNDER_CONSTRUCTION: "Раздел в разработке",
      SELECT_REPORT_FILTERS:
        'Выберите параметры и нажмите "Сформировать отчет"',
      NO_LESSONS:
        'Нет занятий. Проверьте период или создайте занятие кнопкой "Добавить учебное занятие".',
      CONFIRM_DELETE: "Вы уверены, что хотите удалить эту запись?",
      NO_DATA: "Нет данных для отображения",
      DBL_CLICK_HINT:
        "Двойное нажатие - открыть окно обучающегося",
    },
    NOTIFY: {
      SUCCESS_SUMMARY: "Готово",
      SAVED: "Сохранено",
      LESSON_ADDED: "Занятие добавлено",
      LESSON_UPDATED: "Занятие обновлено",
      LESSON_DELETED: "Занятие удалено",
      ATTENDANCE_SAVED: "Посещаемость сохранена",
      ATTENDANCE_DELETED: "Запись о пропуске удалена",
      ROSTER_SAVED: "Список группы скачан",
      VEDOMOST_SAVED: "Ведомость скачана",
    },
    ERRORS: {
      LOGIN: "Ошибка авторизации. Попробуйте еще раз.",
      SAVE_DATA: "Ошибка при сохранении данных",
      SAVE_CONSOLE: "Ошибка при сохранении:",
      ADD_LESSON: "Ошибка при добавлении занятия",
      EDIT_LESSON: "Ошибка при сохранении занятия",
      LESSON_EXISTS: "Учебное занятие на эту дату и пару уже существует.",
      DOWNLOAD_VEDOMOST:
        "Не удалось скачать ведомость. Проверьте наличие шаблона на сервере.",
      DOWNLOAD_STUDENT_CARD:
        "Не удалось скачать выписку из учебной карточки. Проверьте наличие шаблона на сервере.",
      DOWNLOAD_ROSTER:
        "Не удалось скачать список группы. Проверьте наличие шаблона на сервере.",
      LOAD_STUDENTS: "Ошибка при загрузке списка обучающихся.",
      DELETE_LESSON: "Не удалось удалить занятие.",
      GENERATE_REPORT: "Не удалось сформировать отчёт.",
      UNKNOWN_SERVER_ERROR:
        "Неизвестная ошибка сервера. Обратитесь к администратору.",
    },
    ERROR_SUMMARY: "Ошибка",
    HELP: {
      TITLE: "Как ставить отметки",
      LINES: [
        'Сначала выберите группу и учебную дисциплину, затем создайте занятие кнопкой "Добавить учебное занятие". Без занятия отметки ставить некуда.',
        "Одно нажатие на ячейку открывает поле для быстрого проставления отметки путем нажатия цифры на клавиатуре.",
        "Окно обучающегося открывается двойным нажатием на ячейку или нажатием на красную ячейку. В нем можно указать причину отсутствия, поставить основную отметку и добавить пересдачи. Лишнюю отметку можно удалить нажатием на значок корзины.",
        "При одиночном нажатии на ячейку открывается поле для выставления отметки. В нем можно просто нажать клавишу с нужной отметкой на клавиатуре, например 5. Клавиша Enter переходит к следующему обучающемуся.",
        'В окне обучающегося есть кнопки "Назад" и "Далее", поэтому не нужно закрывать окно после каждого человека.',
        "Красная ячейка означает, что обучающийся отсутствует. Причина пропуска написана прямо в ячейке.",
        "Желтая ячейка означает, что там пока нет ни отметки, ни пропуска.",
        'Над списком обучающихся есть быстрые фильтры: "Все", "Без оценок", "С пропусками", "С пересдачами". Рядом находится поиск по фамилии.',
        "Чтобы изменить занятие (дату, тему, преподавателей), нажмите значок карандаша в шапке занятия. В этом окне занятие также можно удалить. Для подтверждения удаления потребуется ввести слово УДАЛИТЬ заглавными буквами. Вместе с занятием удаляются все отметки в нем, а записи посещаемости сохраняются.",
        'Кнопка "Скачать список группы" сохраняет в файл Word список фамилий и инициалов обучающихся группы.',
        "Чтобы скачать зачетно-экзаменационную ведомость (промежуточная аттестация учебной группы), нажмите значок файла в шапке занятия.",
        "Период над сеткой ограничивает показанные занятия по выбранным датам.",
        'При создании занятия укажите дату, время занятия и преподавателей. Часы, вид занятия и преподаватели подставляются из прошлого занятия (можно изменить). Если необходимо выбрать тему прошлого занятия, нажмите на кнопку "Взять тему прошлого занятия" под полем темы.',
      ],
      DONT_SHOW: "Больше не показывать",
      OK: "Понятно",
      OPEN_TITLE: "Как пользоваться журналом",
      ATTENDANCE_TITLE: "Как отмечать посещаемость",
      ATTENDANCE_LINES: [
        'Сначала выберите группу. Период можно выбрать вручную в календаре или кнопками "Эта неделя", "Прошлая неделя", "Следующая неделя". Период ограничен 31 днем.',
        'Нажмите на ячейку, чтобы открыть окно пропуска. Выберите причину и период (только эта пара, несколько пар этого дня или диапазон дней), затем нажмите "Сохранить".',
        'Перед сохранением посмотрите строку "Будет затронуто записей" - там написано, сколько записей изменится.',
        'Чтобы убрать пропуск, нажмите на ячейку с пропуском и выберите "Удалить" в окне.',
        "Зеленым цветом подсвечены ячейки текущего дня.",
        "Вверху находится поиск по фамилии.",
      ],
      REPORTS_TITLE: "Как формировать отчеты",
      REPORTS_LINES: [
        'Выберите вкладку: "Успеваемость" или "Посещаемость".',
        'Укажите полугодие или период, факультет, группу и другие параметры, затем нажмите "Сформировать отчет".',
        'В поле "Обучающийся" можно выбрать одного человека. Там есть поиск по фамилии.',
        "Отчет появляется ниже. Если данных нет, измените параметры и сформируйте отчет заново.",
      ],
    },
    DELETE_LESSON: {
      TITLE: "Удалить занятие?",
      DELETED_WHAT: "Будет удалено безвозвратно:",
      ATTENDANCE_NOTE:
        "Записи посещаемости (пропуски) удалены не будут, это отдельная таблица.",
      IRREVERSIBLE: "Действие необратимо. Восстановить удаленное будет нельзя.",
      RISK: "Вы удаляете занятие на свой риск.",
      CONFIRM_HINT: "Для подтверждения введите слово",
      CONFIRM_WORD: "УДАЛИТЬ",
      MARK_FORMS: ["оценка", "оценки", "оценок"],
      MARK_SUFFIX: "(включая пересдачи)",
    },
  },
};
