export const APP_CONSTANTS = {
  ROUTES: {
    LOGIN: "/login",
    DASHBOARD: "/",
    JOURNAL: "/journal",
    REPORTS: "/reports",
  },
  ROUTE_NAMES: {
    LOGIN: "Login",
    DASHBOARD: "Dashboard",
    JOURNAL: "Journal",
    REPORTS: "Reports",
  },
  API_ENDPOINTS: {
    TOKEN: "/api/token/",
    ME: "/api/users/me/",
    GROUPS: "/api/group/",
    ACTIVE_GROUPS: "/api/group/get_active_groups/",
    SUBJECTS: "/api/subjects/",
    CADETS: "/api/cadet/",
    STUDENTS: "/api/student/",
    CADETS_SHORT: "/api/cadet/short-list/",
    STUDENTS_SHORT: "/api/student/short-list/",
    MARK_VALUES: "/api/mark-values/",
    LESSON_TIMES: "/api/lesson-times/",
    ATTENDANCE_REASONS: "/api/attendance-reasons/",
    LESSONS: "/api/lessons/",
    ATTENDANCES: "/api/attendances/",
    JOURNAL_RECORDS: "/api/journal-records/",
    LESSON_TYPES: "/api/lesson-types/",
    TEACHERS: "/api/readonly-users/",
    SEMESTERS: "/api/semesters/",
    FACULTIES: "/api/subdivision/",
    SPECIALTIES: "/api/speciality/",
    YEARS: "/api/year/",
    REPORTS_PERFORMANCE: "/api/reports/performance/",
    REPORTS_ATTENDANCE: "/api/reports/attendance/",
  },
  FIELD_TYPES: {
    TEXT: "text",
    NUMBER: "number",
    BOOLEAN: "boolean",
    TIME: "time",
    DATE: "date",
    SELECT: "select",
  },
  API_FALLBACK_RESPONSE: { data: [] },
  STORAGE_KEYS: {
    TOKEN: "kis_access_token",
    USER: "kis_user",
  },
  STUDENT_TYPES: {
    CADET: "cadet",
    STUDENT: "student",
  },
  HTTP_STATUS: {
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
  },
  GRID: {
    MIN_COLUMNS: 10,
    MIN_ROWS: 15,
    DEFAULT_PAGINATION_ROWS: 10,
  },
  TIMERS: {
    INLINE_EDIT_DELAY: 250,
    INLINE_EDIT_CLOSE: 150,
  },
  LESSON_HOURS_OPTIONS: [2, 4, 6, 8],
  LOCALES: {
    RU: "ru-RU",
  },
  LOCALE_CONFIG: {
    firstDayOfWeek: 1,
    dayNames: [
      "Воскресенье",
      "Понедельник",
      "Вторник",
      "Среда",
      "Четверг",
      "Пятница",
      "Суббота",
    ],
    dayNamesShort: ["Вск", "Пнд", "Втр", "Срд", "Чтв", "Птн", "Сбт"],
    dayNamesMin: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
    monthNames: [
      "Январь",
      "Февраль",
      "Март",
      "Апрель",
      "Май",
      "Июнь",
      "Июль",
      "Август",
      "Сентябрь",
      "Октябрь",
      "Ноябрь",
      "Декабрь",
    ],
    monthNamesShort: [
      "Янв",
      "Фев",
      "Мар",
      "Апр",
      "Май",
      "Июн",
      "Июл",
      "Авг",
      "Сен",
      "Окт",
      "Ноя",
      "Дек",
    ],
    today: "Сегодня",
    clear: "Очистить",
    dateFormat: "dd.mm.yy",
    weekHeader: "Нед",
  },
  FORMATTING: {
    SEPARATOR: ", ",
    NEWLINE: "\n",
    TIME_SEPARATOR: ":",
    HOUR_FORMAT_24: "24",
  },
  DATE_FORMAT: {
    TWO_DIGIT: "2-digit",
    PAD_CHAR: "0",
    PAD_LENGTH: 2,
  },
  RULES: {
    DATE_RANGE_LENGTH: 2,
    REGEX_MATCH_LENGTH: 2,
    DEFAULT_LESSON_NUMBER: 0,
    TIME_STRING_LENGTH: 5,
    START_OF_DAY_HOURS: 0,
    START_OF_DAY_MINUTES: 0,
    START_OF_DAY_SECONDS: 0,
    START_OF_DAY_MS: 0,
    END_OF_DAY_HOURS: 23,
    END_OF_DAY_MINUTES: 59,
    END_OF_DAY_SECONDS: 59,
    END_OF_DAY_MS: 999,
  },
  PREFIXES: {
    TEMP: "temp-",
    EMPTY_ROW: "empty-row-",
    EMPTY_DATE: "empty-date-",
    EMPTY_SUB: "empty-sub-",
    EMPTY_COL: "empty-col-",
    HEADER: "header-",
  },
  CSS_SELECTORS: {
    INLINE_EDITOR_INPUT: ".inline-editor input",
  },
  API_ERRORS: {
    UNIQUE_SET: "must make a unique set",
    LESSON_TIME: "lesson_time",
  },
  API_ERROR_KEYS: {
    DETAIL: "detail",
    ERROR: "error",
    NON_FIELD_ERRORS: "non_field_errors",
  },
  REPORT_FILTERS: {
    ALLOWED_FACULTIES: [2, 3, 8, 13, 15],
    ALLOWED_SPECIALTIES: [1, 2, 10],
  },
  ERROR_TRANSLATIONS: {
    "This field is required.": "Это поле обязательно для заполнения.",
    "must make a unique set": "Запись с такими параметрами уже существует.",
    lesson_time: "Время учебного занятия",
    date: "Дата",
    subject: "Дисциплина",
    group: "Группа",
    hours: "Количество учебных часов",
  },
  REPORT_TABS: {
    PERFORMANCE: "performance",
    ATTENDANCE: "attendance",
  },
  UI: {
    APP_TITLE: "Электронный журнал",
    LOGIN_SUBTITLE: "Войдите в свой аккаунт",
    DASHBOARD_TITLE: "Выберите раздел",
    LESSON_SUFFIX: "",
    DEFAULT_ATTENDANCE: "Не указано (Присутствует)",
    DEFAULT_MARK: "Нет отметки",
    NO_TOPIC: "Без темы",
    BREADCRUMB_SEPARATOR: "/",
    CRUD_DIALOG_WIDTH: "450px",
    PAGE_TITLES: {
      Journal: "Журнал",
      Reports: "Отчетность",
    },
    LABELS: {
      HOME: "Главная",
      USERNAME: "Имя пользователя",
      PASSWORD: "Пароль",
      LOGIN_BTN: "Авторизоваться",
      LOGOUT_BTN: "Выйти",
      JOURNAL: "Журнал",
      REPORTS: "Отчетность",
      GROUP: "Группа",
      FACULTY: "Факультет",
      SPECIALTY: "Специальность",
      SUBJECT: "Дисциплина",
      DATE: "Дата",
      LESSON_TIME: "Пара",
      LESSON_TYPE: "Вид учебного занятия / форма аттестации",
      TOPIC: "Тема учебного занятия",
      TEACHERS: "Преподаватели",
      ATTENDANCE: "Посещаемость",
      MARK: "Отметка",
      MARK_VALUE: "Отметка",
      MAIN_MARK: "Основная:",
      RETAKE_MARK: "Пересдача",
      ADD_RETAKE: "Добавить пересдачу",
      ADD_MARK: "Добавить отметку",
      FULL_NAME: "ФИО",
      ABSENT: "Отсутствует",
      CANCEL: "Отмена",
      SAVE: "Сохранить",
      ADD: "Добавить",
      EDIT: "Редактировать",
      DELETE: "Удалить",
      ACTIONS: "Действия",
      ADD_LESSON: "Добавить учебное занятие",
      FILTERS: "Фильтры",
      CLEAR_FILTERS: "Очистить фильтры",
      ATTENDANCE_REASONS: "Причина пропуска",
      REASON: "Причина",
      SEMESTER: "Полугодие",
      DATE_RANGE: "Период (С - ПО)",
      STUDENT: "Обучающийся",
      TEACHER: "Преподаватель",
      GENERATE_REPORT: "Сформировать отчет",
      TAB_PERFORMANCE: "Успеваемость",
      TAB_ATTENDANCE: "Посещаемость",
      YEAR: "Учебный год",
      YEAR_STR: "Учебный год (прописью)",
      START_TIME: "Время начала",
      END_TIME: "Время окончания",
      IS_ABSENT: "Считается отсутствием",
      START_DATE: "Дата начала",
      END_DATE: "Дата окончания",
      HOURS: "Количество учебных часов",
      PERIOD: "Период",
      SEARCH_BY_NAME: "Поиск по ФИО",
      OK: "OK",
      LEGEND: "",
      CURRENT_MARK: "Текущая отметка",
      RETAKEN_MARK: "Пересданная отметка",
    },
    PLACEHOLDERS: {
      SELECT_GROUP: "-- Выберите группу --",
      SELECT_FACULTY: "-- Выберите факультет --",
      SELECT_SPECIALTY: "-- Выберите специальность --",
      SELECT_SUBJECT: "-- Выберите дисциплину --",
      SELECT_LESSON_TIME: "Выберите пару",
      SELECT_DATE: "Выберите дату",
      SELECT_TEACHERS: "Выберите преподавателей",
      SELECT_SEMESTER: "-- Выберите полугодие --",
      SELECT_STUDENT: "-- Выберите обучающегося --",
      SELECT_TEACHER: "-- Выберите преподавателя --",
      SELECT_MARK: "-- Выберите отметку --",
      SELECT_REASON: "-- Выберите причину --",
      SELECT_LESSON_TYPE: "-- Выберите вид учебного занятия --",
      SELECT_HOURS: "Выберите кол-во учебных часов",
      SEARCH_BY_NAME: "Поиск по ФИО...",
    },
    MESSAGES: {
      SELECT_FILTERS: "Выберите группу и дисциплину",
      LOADING: "Загрузка данных...",
      SAVING: "Сохранение...",
      NO_MARKS: "Нет отметок",
      UNDER_CONSTRUCTION: "Раздел в разработке",
      SELECT_REPORT_FILTERS:
        'Выберите параметры и нажмите "Сформировать отчет"',
      CONFIRM_DELETE: "Вы уверены, что хотите удалить эту запись?",
      NO_DATA: "Нет данных для отображения",
    },
    ERRORS: {
      LOGIN: "Ошибка авторизации. Попробуйте еще раз.",
      SAVE_DATA: "Ошибка при сохранении данных",
      ADD_LESSON: "Ошибка при добавлении занятия",
      LESSON_EXISTS: "Учебное занятие на эту дату и пару уже существует.",
      DOWNLOAD_VEDOMOST:
        "Не удалось скачать ведомость. Проверьте наличие шаблона на сервере.",
      LOAD_STUDENTS: "Ошибка при загрузке списка обучающихся.",
      UNKNOWN_SERVER_ERROR:
        "Неизвестная ошибка сервера. Обратитесь к администратору.",
    },
    ERROR_SUMMARY: "Ошибка",
  },
};
